# Конфигурационный файл для Netlify

[build]
  # Папка, в которой находятся ваши API-функции
  functions = "api"
  # Папка, которую нужно развернуть как статический сайт
  publish = "public"

# Правила для перенаправления, чтобы API были доступны по коротким путям
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200