{
  "version": 1,
  "deployment": {
    "framework": "static",
    "build": {
      "command": "",
      "directory": ".",
      "environment": {}
    }
  },
  "preview": {
    "alias": ["rdf-rocky-bot-preview"]
  },
  "headers": [
    {
      "source": "**/*.html",
      "headers": [
        {
          "key": "Cache-Control",
          "value": "no-cache, no-store, must-revalidate"
        }
      ]
    },
    {
      "source": "**/*.(js|css)",
      "headers": [
        {
          "key": "Cache-Control", 
          "value": "public, max-age=31536000, immutable"
        }
      ]
    }
  ]
}